# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jcr/IST/MEng/PSD/Projects/Lab3/Lab3.srcs/sources_1/ip/middle_memory/middle_memory.xci
# IP: The module: 'middle_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcr/IST/MEng/PSD/Projects/Lab3/Lab3.gen/sources_1/ip/middle_memory/middle_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'middle_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jcr/IST/MEng/PSD/Projects/Lab3/Lab3.srcs/sources_1/ip/middle_memory/middle_memory.xci
# IP: The module: 'middle_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcr/IST/MEng/PSD/Projects/Lab3/Lab3.gen/sources_1/ip/middle_memory/middle_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'middle_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
