# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jcr/IST/MEng/PSD/Projects/Lab3/project_1.srcs/sources_1/ip/weights1/weights1.xci
# IP: The module: 'weights1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcr/IST/MEng/PSD/Projects/Lab3/project_1.gen/sources_1/ip/weights1/weights1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jcr/IST/MEng/PSD/Projects/Lab3/project_1.srcs/sources_1/ip/weights1/weights1.xci
# IP: The module: 'weights1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jcr/IST/MEng/PSD/Projects/Lab3/project_1.gen/sources_1/ip/weights1/weights1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
