# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/P3/Basys3_Master.xdc

# IP: ip/middle_memory/middle_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_memory || ORIG_REF_NAME==middle_memory} -quiet] -quiet

# IP: ip/weights2/weights2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weights2 || ORIG_REF_NAME==weights2} -quiet] -quiet

# IP: ip/weights1/weights1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weights1 || ORIG_REF_NAME==weights1} -quiet] -quiet

# IP: ip/images_mem/images_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==images_mem || ORIG_REF_NAME==images_mem} -quiet] -quiet

# XDC: c:/Users/Francisco/OneDrive/rea de Trabalho/IST-PSD/Lab3-upgraded/project_1.gen/sources_1/ip/middle_memory/middle_memory_ooc.xdc

# XDC: c:/Users/Francisco/OneDrive/rea de Trabalho/IST-PSD/Lab3-upgraded/project_1.gen/sources_1/ip/weights2/weights2_ooc.xdc

# XDC: c:/Users/Francisco/OneDrive/rea de Trabalho/IST-PSD/Lab3-upgraded/project_1.gen/sources_1/ip/weights1/weights1_ooc.xdc

# XDC: c:/Users/Francisco/OneDrive/rea de Trabalho/IST-PSD/Lab3-upgraded/project_1.gen/sources_1/ip/images_mem/images_mem_ooc.xdc
