#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 11 17:58:24 WEST 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim circuito_tb_time_impl -key {Post-Implementation:sim_1:Timing:circuito_tb} -tclbatch circuito_tb.tcl -view /home/jbcr/Desktop/IST/MEng/PSD/Projects/Lab2/circuito_tb_time_impl.wcfg -log simulate.log"
xsim circuito_tb_time_impl -key {Post-Implementation:sim_1:Timing:circuito_tb} -tclbatch circuito_tb.tcl -view /home/jbcr/Desktop/IST/MEng/PSD/Projects/Lab2/circuito_tb_time_impl.wcfg -log simulate.log

