# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab2/Basys3_Master.xdc

# IP: ip/middle_memory/middle_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_memory || ORIG_REF_NAME==middle_memory} -quiet] -quiet
