# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/P3/Basys3_Master.xdc

# IP: ip/weights1/weights1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==weights1 || ORIG_REF_NAME==weights1} -quiet] -quiet

# IP: ip/images_mem/images_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==images_mem || ORIG_REF_NAME==images_mem} -quiet] -quiet
